### ISSUE TITLE
Cannot move 

### ISSUE THREAD

**Issue by tuanphpvn** [plutov/go-snake-telnet#6]
![error-snake](https://user-images.githubusercontent.com/7608580/31755139-be220f24-b4c6-11e7-80da-ddedd4425eb7.png)

The game cannot play because cannot move around.

Enviroment:

OS: Ubuntu 16.04, (64bit)
Terminal: Default

**Comment by plutov** [comment]
Hi @tuanphpvn can you please let me know how do you move it? Did you try type `d` and press `Enter`?

**Comment by tuanphpvn** [comment]
I use navigation key (left, right, bottom, up)

**Comment by plutov** [comment]
@tuanphpvn it will not work, because it's a telnet, you need to send key to server. So instruction says `Move: w a s d + Enter`

**Comment by tuanphpvn** [comment]
Thanks. I will try again.
